version: "3"
services:
  yard-docs:
    build: .
    command: bundle exec yard server --reload
    ports:
      - 9999:8808
    volumes:
      - .:/src
      - bundle:/bundle

  test:
    build: .
    command: bundle exec guard --no-bundler-warning --no-interactions
    volumes:
      - .:/src
      - bundle:/bundle
    environment:
      - TEST_DB_URL=postgres://postgres@db/pg_conduit_src_test
    links:
      - db

  db:
    image: postgres:9.6.6
    ports:
      - 5499:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  bundle:
  database:
